--- 
jobs: 
  build: 
    docker: 
      - 
        image: "rikorose/gcc-cmake:latest"
    steps: 
      - checkout
      - 
        run: "apt-get update"
      - 
        run: "apt-get install -y libncurses5-dev libncursesw5-dev"
      - 
        run: 
          command: "cmake ."
          name: "init cmake"
      - 
        run: 
          command: "cmake --build . -- -j 2"
          name: "build application"
    working_directory: ~/project
version: 2
workflows: 
  build: 
    jobs: 
      - 
        build: 
          filters: 
            branches: 
              only: 
                - master
                - circleci
  version: 2
